### ISSUE TITLE
Error when adding 1 and removing it on iOS

### ISSUE THREAD

**Issue by freerk92** [CrossGeeks/ToolbarItemBadgeSample#1]
When using the Sample I press + once and then -, after which I can't do anything anymore.
The output gives me the error:
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.

**Comment by ali-h2010** [comment]
I am getting the same issue 
error is in the handle value but I am not sure how to fix it 
BarButtonItemExtensions.cs
`
static CAShapeLayer GetBadgeLayer(UIBarButtonItem barButtonItem)
    {
        var handle = objc_getAssociatedObject(barButtonItem.Handle, BadgeKey.Handle);

            if (handle != IntPtr.Zero)
            {
                var value = ObjCRuntime.Runtime.GetNSObject(handle);
                if (value != null)
                    return value as CAShapeLayer;
                else
                    return null;
            }
            return null;
        }`

**Comment by ali-h2010** [comment]
@freerk92
I found a temporary solution which is to comment the lines that remove the badge when the number is 0.
BarButtonItemExtensions.cs
` public static void UpdateBadge(this UIBarButtonItem barButtonItem, string text, UIColor backgroundColor, UIColor textColor)
        {
            var bLayer = GetBadgeLayer(barButtonItem);

            //if (string.IsNullOrEmpty(text) || text == "0")
            //{
            //    bLayer?.RemoveFromSuperLayer();

            //    objc_setAssociatedObject(barButtonItem.Handle, BadgeKey.Handle, new CAShapeLayer().Handle, AssociationPolicy.ASSIGN);
            //    return;
            //}

            var textLayer = bLayer?.Sublayers?.First(p => p is CATextLayer) as CATextLayer;
            if (textLayer != null)
            {
                textLayer.String = text;
            }
            else
            {
                barButtonItem.AddBadge(text, backgroundColor, textColor);
            }
        }`
The issue is that, when the number reaches 0 , the developer was removing the reference to that budge. which will prevent the adding to it and case the crash.  The correct action is to create a new budge but I don't know how to do it without breaking the code

**Comment by joalcego** [comment]
I am getting the same issue too.

Thanks @ali-h2010! Your suggestion is working. I just replaced the commented code with the following one to make sure plugin behavior is consistent:

```
if (bLayer != null)
{
      bLayer.Hidden = String.IsNullOrEmpty(text) || text == "0";
      if(bLayer.Hidden) 
      {
            return;    
      }
}
```

**Comment by ali-h2010** [comment]
@joalcego , Thanks for the update. It's working great.

**Comment by rdelrosario** [comment]
Thanks! @joalcego just updated the code with this fix.
