### ISSUE TITLE
Issue at Resource.Dimension.textsize_badge_count in Drawble class

### ISSUE THREAD

**Issue by susantadotnet** [CrossGeeks/ToolbarItemBadgeSample#13]
1.i am getting object reference not set to an object at Resource Dimension in Drawble class, Please refer below attached image for more details.
2. issue is getting at      : float oneDp = 1 * _context.Resources.DisplayMetrics.Density;<---------
Note: Even i added the dimens.xml file also i am getting the same issue.

![Capture](https://user-images.githubusercontent.com/70484650/91666232-c54b2480-eb18-11ea-99ad-42cc8de7e138.PNG)

Please help me on this.

**Comment by AlvinKwong** [comment]
Not sure the cause of the error. Maybe you can check:
1. Is the context null? Use a breakpoint on this line to see if the context parameter is null or not.
2. Is the dimens.xml file's property set to Android resource?
3. Does the Resource.designer.cs contain this property? If so, when you move the cursor to "textsize_badge_count", it should show its resource id. Note that this file is generated automatically. When you create the dimens.xml and the value is set properly, building the Droid project should automatically generate the id for this property.
![Screen Shot 2020-08-31 at 17 29 19](https://user-images.githubusercontent.com/31871670/91700028-296cf780-ebb0-11ea-9729-9843cc71a1fd.png)

**Comment by susantadotnet** [comment]
Yes have verified the context is coming null,
I have applied the new changes what you mentioned due to cross platform.current.activity issue

**Comment by susantadotnet** [comment]
Thanks, I solved it modified the context code.
