### ISSUE TITLE
Not working under iOS Tabbed Page

### ISSUE THREAD

**Issue by paulusyeung** [CrossGeeks/ToolbarItemBadgeSample#2]
Same code works under android but not iOS.

iOS version 11.4

`public class ToolbarItemBadgeService : IToolbarItemBadgeService
    {
        public void SetBadge(Page page, ToolbarItem item, string value, Color backgroundColor, Color textColor)
        {
            Device.BeginInvokeOnMainThread(() =>
            {
                var renderer = Platform.GetRenderer(page);
                if (renderer == null)
                {
                    renderer = Platform.CreateRenderer(page);
                    Platform.SetRenderer(page, renderer);
                }
                var vc = renderer.ViewController;

                var rightButtomItems = vc?.ParentViewController?.NavigationItem?.RightBarButtonItems;
                var idx = page.ToolbarItems.IndexOf(item);

                if (rightButtomItems != null && rightButtomItems.Length > idx)
                {
                    var barItem = rightButtomItems[idx];
                    if (barItem != null)
                    {
                        barItem.UpdateBadge(value, backgroundColor.ToUIColor(), textColor.ToUIColor());
                    }
                }

            });
        }
    }`

rightButtomItems always null when using master details tabbed page.

**Comment by HamidBaghernia** [comment]
Hi, same here.
    var rightButtomItems = vc?.ParentViewController?.NavigationItem?.RightBarButtonItems;
is always null.

**Comment by cassionandi** [comment]
Same here

**Comment by alexstrong29** [comment]
Did anyone get a fix for this? I am experiencing the same issue. Although using FreshMVVM and a master detail container

**Comment by ghost** [comment]
Any solution for this issue?

var rightButtomItems = vc?.ParentViewController?.NavigationItem?.RightBarButtonItems;

rightButtomItems is always null for content page with tabbedpage.
