### ISSUE TITLE
IOS BarButtonItemExtensions this class error 

### ISSUE THREAD

**Issue by chGalbadrakh** [CrossGeeks/ToolbarItemBadgeSample#4]
[DllImport(Constants.ObjectiveCLibrary)] how to fix it.. 
![error](https://user-images.githubusercontent.com/17295812/44697978-b3a98f00-aab0-11e8-80a5-f2a4a5835dfc.PNG)

**Comment by rdelrosario** [comment]
Import namespace: using ObjCRuntime;
