### ISSUE TITLE
[Android] "textsize_badge_count" error

### ISSUE THREAD

**Issue by Cobry** [CrossGeeks/ToolbarItemBadgeSample#5]
I got an error with android version. In the "BadgeDrawable.cs" file, at the line 26 content a variable named "textsize_badge_count" which do not exist.
In fact if we search this variable in the file named "Resoruce.designer.cs" it do not exist.
Do you have a solution for me ?

**Comment by rdelrosario** [comment]
This does exists is in:

https://github.com/CrossGeeks/ToolbarItemBadgeSample/blob/master/ToolbarItemBadgeSample/ToolbarItemBadgeSample.Android/Resources/values/dimens.xml
