### ISSUE TITLE
N

### ISSUE THREAD

**Issue by Monikaprime** [CrossGeeks/ToolbarItemBadgeSample#7]
Have Written same code but error "System.NullReferenceException: Object reference not set to an instance of an object." coming at line var toolbar = CrossCurrentActivity.Current.Activity.FindViewById(Resource.Id.toolbar) as Android.Support.V7.Widget.Toolbar; in ToolbarItemBadgeService in .Android project

please help

**Comment by eliyasbaby** [comment]
@Monikaprime Did you get any solution for this?

**Comment by Monikaprime** [comment]
No created a control with relative layout and used an image and label

**Comment by AlvinKwong** [comment]
I have found a solution and commented on another thread. Please check if it works
https://github.com/CrossGeeks/ToolbarItemBadgeSample/issues/11#issuecomment-669008974
